import html,secrets
from pathlib import Path
from datetime import datetime,timezone
from aiohttp import web
import discord
from config import GUILD_ID,DISCORD_INVITE_URL
from database.db import create_web_application,get_web_application_by_token,get_setting
from cogs.web_applications import WebApplicationReviewView
A=Path(__file__).parent/"web_assets"
RULES=[("الالتزام بالزي الرسمي","يجب الالتزام بالزي الرسمي المعتمد للمطعم طوال فترة العمل."),("منع الأعمال الإجرامية بالزي الرسمي","يُمنع القيام بأي عمل إجرامي أثناء ارتداء الزي الرسمي، ومخالفة ذلك يترتب عليها الفصل."),("احترام الزبائن وحسن التعامل","يُمنع التعامل بقلة أدب أو حدة مع أي زبون."),("التعامل مع المشاكل","عند حدوث مشكلة ارجع للمشرف وتجنب الجدال."),("تمثيل المطعم","أسلوبك يعكس صورتك وصورة Bean Machine."),("الوجبات المجانية","لكل موظف 10 وجبات مجانية فقط."),("منع البيع المجاني","يُمنع البيع المجاني خارج الصلاحيات المسموحة."),("الأسعار الرسمية","يجب الالتزام بالأسعار المعتمدة دون زيادة أو نقصان."),("المطعم منطقة آمنة","يُمنع التهديد أو القتل أو الأعمال العدائية داخل المطعم."),("التعامل مع المخالفات","ارفع المخالفة للإدارة ولا ترد عليها بمخالفة."),("استغلال الصلاحيات","يُمنع استغلال الوظيفة لتحقيق منفعة شخصية."),("تسجيل الدخول والخروج","يجب تسجيل الدخول عند بدء العمل والخروج عند الانتهاء."),("التلاعب بالفواتير","يُمنع إنشاء أو تكرار فواتير وهمية."),("تعليمات الإدارة","يجب الالتزام بتوجيهات المشرفين والإدارة.")]
CSS='*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#382316,#090705 38%);color:#f5eadc;font-family:Tahoma,Arial;direction:rtl}.w{width:min(1120px,92%);margin:auto}nav{position:sticky;top:0;background:#0b0806ed;border-bottom:1px solid #352418;z-index:5}.n{height:76px;display:flex;align-items:center;justify-content:space-between;gap:18px}.b{display:flex;align-items:center;gap:10px;color:#e4b97f}.b img{width:48px}.links{display:flex;gap:22px}.links a,.btn{color:#f5eadc;text-decoration:none}.st{border:1px solid #5a3d28;border-radius:30px;padding:9px 14px;color:#e4b97f}.hero{text-align:center;padding:65px 0 35px}.hero img{width:160px}.hero h1{color:#e4b97f;font-size:48px}.hero p,.card p,li{color:#b9a58f;line-height:1.85}.grid,.rules{display:grid;grid-template-columns:1fr 1fr;gap:14px}.card{background:linear-gradient(#17100c,#21170f);border:1px solid #4d3422;border-radius:18px;padding:22px;margin-bottom:14px}.btn{display:inline-block;background:linear-gradient(90deg,#dba76b,#efc78e);color:#1b1109;border:0;border-radius:11px;padding:13px 19px;font-weight:bold;cursor:pointer}.sec{padding:45px 0}.title{text-align:center;color:#e4b97f;font-size:34px}.step{display:grid;grid-template-columns:1fr 1.1fr;gap:22px;align-items:center}.step img{width:100%;border-radius:13px;border:1px solid #493321}.num{color:#e4b97f;font-weight:bold}input,textarea,select{width:100%;background:#0d0907;border:1px solid #4b3424;border-radius:10px;padding:13px;color:white;font:inherit;margin:7px 0 16px}textarea{min-height:105px}.notice{text-align:center}.ok{color:#72c28f}.bad{color:#d97676}@media(max-width:800px){.links{display:none}.grid,.rules,.step{grid-template-columns:1fr}.hero h1{font-size:38px}}'
def status(row):
 if not row:return "لم تقدم بعد"
 return {"pending":"قيد المراجعة","accepted":"مقبول مبدئيًا","rejected":"مرفوض — يمكنك إعادة التقديم"}.get(row[10],"تم الاستكمال")
def lay(body,row=None):return f"<!doctype html><html lang=ar><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'><style>{CSS}</style></head><body><nav><div class='w n'><div class=b><img src=/assets/logo.png><b>BEAN MACHINE</b></div><div class=links><a href=/>الرئيسية</a><a href=/guide>دليل العمل</a><a href=/rules>القوانين</a><a href=/apply>التقديم</a></div><div class=st>حالة طلبك: {status(row)}</div></div></nav>{body}</body></html>"
async def cur(r):
 t=r.cookies.get("bm_application");return await get_web_application_by_token(t) if t else None
async def home(r):
 row=await cur(r);can=not row or row[10]=="rejected";ab='<a class=btn href=/rules>ابدأ التقديم</a>' if can else '<span class=st>لديك طلب حالي</span>';return web.Response(text=lay(f"<main class=w><section class=hero><img src=/assets/logo.png><h1>BEAN MACHINE</h1><p>بوابة التقديم ودليل العمل الرسمي.</p></section><section class=grid><div class=card><h2>التقديم</h2><p>التقديم بالكامل من الموقع، وبعد الإرسال تتابع طلبك من بوت Discord.</p>{ab}</div><div class=card><h2>دليل العمل</h2><p>مرجع دائم للموظفين بالخطوات والصور.</p><a class=btn href=/guide>فتح الدليل</a></div></section></main>",row),content_type="text/html")
async def rules(r):
 row=await cur(r);cards=''.join(f"<div class=card><span class=num>{i:02}</span><h3>{html.escape(t)}</h3><p>{html.escape(d)}</p></div>" for i,(t,d) in enumerate(RULES,1));btn='<a class=btn href=/apply>أوافق وأكمل التقديم</a>' if not row or row[10]=='rejected' else '';return web.Response(text=lay(f"<main class='w sec'><h1 class=title>قوانين Bean Machine</h1><div class=rules>{cards}</div><div class=notice>{btn}</div></main>",row),content_type='text/html')
async def guide(r):
 row=await cur(r);body="""<main class='w sec'><h1 class=title>دليل العمل</h1><div class='card step'><div><h2>1 — تسجيل الدخول وفتح المطعم</h2><p>من المكتب داخل المطعم: <b>Sign in / out</b> لتسجيل الدخول والخروج، و<b>Turn On/Off</b> لفتح وإغلاق المطعم على الخريطة.</p></div><img src='/assets/01-office.png'></div><div class='card step'><div><h2>2 — تصوير المخزون</h2><p>توجه إلى Stash وافتح المخزون وخذ صورة واضحة وكاملة. بعدها Discord ← لوحة التحكم ← تسجيل دخول وأرفق الصورة. عند الخروج صوّر المخزون مرة ثانية ثم اضغط تسجيل خروج وأرفق الصورة.</p></div><div><img src='/assets/02-stash-location.png'><br><br><img src='/assets/03-stash-photo.png'></div></div><div class='card step'><div><h2>3 — الكاشير والفواتير</h2>
<div style='display:grid;gap:12px;margin-top:16px'>
<div><b>Edit Invoice</b><br><span style='color:var(--muted)'>لتعديل فاتورة تم إنشاؤها مسبقًا.</span></div>
<div><b>Cancel Invoice</b><br><span style='color:var(--muted)'>لإلغاء فاتورة تم إنشاؤها.</span></div>
<div><b>Give Beanmachine Menu</b><br><span style='color:var(--muted)'>لإعطاء المنيو لشخص بعد إدخال الـ ID الخاص به.</span></div>
<div><b>Manage Company</b><br><span style='color:var(--muted)'>خاص بالإدارة فقط ولا يُسمح للموظف باستخدامه.</span></div>
<div><b>Create Order</b><br><span style='color:var(--muted)'>إنشاء فاتورة: Create Order ← Add Item ← اختر منتج ← Charge Customer ← أدخل قيمة الفاتورة وCustomer ID ← صوّر الشاشة ← أرسل الصورة من زر إنشاء فاتورة في لوحة التحكم.</span></div>
</div></div><div><img src='/assets/04-cashier-menu.png'><br><br><img src='/assets/09-invoice.png'></div></div><div class='card step'><div><h2>4 — تصنيع الحلويات</h2><p>اختر المنتج لمعرفة المكونات، واشتر النواقص من Store. حدد Amount ثم Craft. الحد الأقصى 50 عنصر ويستغرق 150 ثانية، ولا يمكنك التحرك أو تنفيذ أي عمل أثناء التصنيع.</p></div><div><img src='/assets/10-crafting-menu.png'><br><br><img src='/assets/11-store.png'><br><br><img src='/assets/12-craft-amount.png'></div></div></main>""";return web.Response(text=lay(body,row),content_type='text/html')
async def apply_get(r):
 row=await cur(r)
 if row and row[10]!='rejected':raise web.HTTPFound('/')
 f="""<main class='w sec'><div class=card><h1 class=title>نموذج التقديم</h1><form method=post><label>Discord ID</label><input name=discord_id pattern='[0-9]{15,22}' required><label>ليش حاب تنضم إلى Bean Machine؟</label><textarea name=reason required></textarea><label>كم ساعة تقدر تشتغل باليوم؟</label><input name=daily_hours required><label>وش الأوقات اللي غالبًا تكون متواجد فيها؟</label><input name=availability required><label>هل سبق واشتغلت في مطعم أو وظيفة داخل المدينة؟ إذا نعم، اذكرها.</label><textarea name=previous_experience required></textarea><label>كيف تتصرف لو واجهت زبون متعصب أو قليل أدب؟</label><textarea name=difficult_customer required></textarea><label>هل أنت مستعد للالتزام بأنظمة المطعم واللبس الرسمي؟</label><select name=uniform_commitment required><option>نعم</option><option>لا</option></select><label>هل قرأت جميع قوانين العمل وتوافق عليها؟</label><select name=rules_agreement required><option>نعم</option><option>لا</option></select><button class=btn>إرسال الطلب</button></form></div></main>""";return web.Response(text=lay(f,row),content_type='text/html')
async def apply_post(r):
 row=await cur(r)
 if row and row[10]!='rejected':raise web.HTTPFound('/')
 d=await r.post()
 try:did=int(d.get('discord_id',''))
 except:return web.Response(text='Discord ID غير صحيح',status=400)
 keys=['reason','daily_hours','availability','previous_experience','difficult_customer','uniform_commitment','rules_agreement'];a={k:str(d.get(k,'')).strip() for k in keys}
 if not all(a.values()) or a['uniform_commitment']!='نعم' or a['rules_agreement']!='نعم':return web.Response(text='يجب تعبئة الحقول والموافقة على الأنظمة',status=400)
 token=secrets.token_urlsafe(32);app=await create_web_application(GUILD_ID,did,a,token,datetime.now(timezone.utc).isoformat());g=r.app['bot'].get_guild(GUILD_ID)
 if g:
  rid=await get_setting(GUILD_ID,'application_review');ch=g.get_channel(int(rid)) if rid else None
  if isinstance(ch,discord.TextChannel):
   e=discord.Embed(title='📝 طلب تقديم جديد من الموقع',timestamp=datetime.now(timezone.utc));vals=[('المتقدم',f'<@{did}>\n`{did}`'),('سبب الانضمام',a['reason']),('ساعات العمل',a['daily_hours']),('أوقات التواجد',a['availability']),('الخبرة',a['previous_experience']),('التعامل مع العميل',a['difficult_customer'])]
   for n,v in vals:e.add_field(name=n,value=v[:1024],inline=False)
   await ch.send(embed=e,view=WebApplicationReviewView(app))
 invite=html.escape(DISCORD_INVITE_URL,quote=True);join=f"<a class=btn href='{invite}' target=_blank>دخول سيرفر Discord</a>" if invite else '<p>رابط السيرفر غير مضبوط.</p>';body=f"<main class='w sec'><div class='card notice'><h1 class=ok>تم إرسال طلبك بنجاح</h1><p>ادخل Discord وتوجه إلى روم متابعة التقديم واضغط <b>📋 متابعة طلبي</b>. لا تحتاج رقم أو رمز؛ البوت يتعرف عليك من Discord ID.</p>{join}<p>يمكنك الرجوع للموقع في أي وقت لمراجعة دليل العمل.</p></div></main>";resp=web.Response(text=lay(body,(0,0,0,0,0,0,0,0,0,0,'pending')),content_type='text/html');resp.set_cookie('bm_application',token,max_age=31536000,httponly=True,samesite='Lax');return resp
async def start_web_server(bot,port):
 app=web.Application();app['bot']=bot;app.router.add_static('/assets/',A);app.router.add_get('/',home);app.router.add_get('/guide',guide);app.router.add_get('/rules',rules);app.router.add_get('/apply',apply_get);app.router.add_post('/apply',apply_post);runner=web.AppRunner(app);await runner.setup();await web.TCPSite(runner,'0.0.0.0',port).start();return runner
